### ISSUE TITLE
Telegram code not arriving

### ISSUE THREAD

**Issue by janyf** [proseltd/Telepathy-Community#76]
Hello , 

I am unable to receive token from telegram, did anyone encounter similar issue ? 

I tried two different api registrations + phone numbers , but token not arrived.

Is there any logs , where i could check what could be wrong , if telepathy is sending any request to telegram

**Comment by sufsblue** [comment]
same issues,
need help to login through telegram
please advice on how to login to telegram

**Comment by janyf** [comment]
my fault , you need to simply put phone number again ... , not sure why it was not working before though , because i try it
